[workspace]
resolver = "2"
members = [
  #"module/rust/*",
  #"module/alias/*",
  #"module/move/*",
  "sample/rust/*",
]
exclude = [
  "*",
  #"module/move/_video_experiment",
  # "module/rust/-*",
  # "sample/rust/-*",
  # "module/rust/_*",
  # "sample/rust/_*",
  # "sample/rust/_select_matching",
]
# default-members = [ "module/rust/wtools" ]
